baseURL = "https://rezepte.notjakob.com"
languageCode = "de"
defaultContentLanguage = "de"
title = "Jakobs Rezeptbuch"
theme = "dream"

# copyright = ""

enableRobotsTXT = true

[params]
  background = "#FFEEDD"
  # backgroundImage = "/img/bg.jpg"
  linkColor = "seagreen"

  author = "Jakob"
  headerTitle = "Jakobs Rezeptbuch"
  avatar = "/img/avatar.png"
  
  twitter = "fyrwit77"
  instagram = "jakobnotjakob/"
  github = "fyr77"

  siteStartYear = 2020

  # search
  enableSearch = true
  
  utterancesRepo = "fyr77/rezepte"
  
  darkLinkColor = "darkseagreen"
  backgroundDark = "black"
  darkNav = true 
  dark404 = true
